#========================================
# Test profile settings (IT tests)
#========================================
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:sqlserver:2019-CU28-ubuntu-20.04:///
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/scripts/cleanup.sql,classpath:db/scripts/testdata.sql
      encoding: utf-8
      mode: always
  security:
    oauth2:
      client:
        provider:
          employee:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          employee:
            client-id: the-client-id
            client-secret: the-client
logging:
  level:
    root: INFO
integration:
  employee:
    url: http://localhost:${wiremock.server.port:}/api-employee